{% metadata_file .yamato/Globals.metafile %}
---
name: Build and Test Linux x64

agent:
  type: Unity::VM
  image: platform-foundation/linux-ubuntu-18.04-mono-bokken:0.1.7-978398
  flavor: b1.large

variables:
  ARTIFACT_FILENAME: {{globals.artifact_base_name}}-linux-x64.7z

commands:
  - chmod 755 .yamato/scripts/build_linux_x64.sh
  - chmod 755 .yamato/scripts/test_linux_x64.sh
  - ./.yamato/scripts/build_linux_x64.sh
  - ./.yamato/scripts/test_linux_x64.sh

artifacts:
  7z-archives:
    paths:
      - artifacts/unity/**
  build:
    paths:
      - artifacts/bin/**

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
