{% metadata_file .yamato/Globals.metafile %}
---
name: Build and Test Windows x86

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:v1.1.7-1038262
  flavor: b1.xlarge

variables:
  ARTIFACT_FILENAME: {{globals.artifact_base_name}}-win-x86.7z

commands:
  - .yamato/scripts/build_windows_x86.cmd
  - .yamato/scripts/test_windows_x86.cmd

artifacts:
  7z-archives:
    paths:
      - artifacts\unity\**
  build:
    paths:
      - artifacts\bin\**

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"