name: Build and Test Linux x64

agent:
  type: Unity::VM
  image: platform-foundation/linux-ubuntu-18.04-mono-bokken:latest
  flavor: b1.large

commands:
  - ./build.sh -subset clr+libs+libs.tests -test -a x64 -c release -ci -ninja
  - ./build.sh -subset host+packs -a x64 -c release
  - command: ./src/tests/build.sh x64 release ci
    retries: 1
  - ./src/tests/run.sh x64 release
  - ./build.sh clr.paltests
  - ./artifacts/bin/coreclr/$(uname).x64.Debug/paltests/runpaltests.sh $(pwd)/artifacts/bin/coreclr/$(uname).x64.Debug/paltests

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"

artifacts: 
  linux64:
    paths:
      - artifacts/packages/Release/Shipping/dotnet-runtime-7.0.0-dev-linux-x64.tar.gz
