{% metadata_file .yamato/Globals.metafile %}
---
name: Build and Test (banned) OSX ARM64

agent:
  type: Unity::VM::osx
  image: platform-foundation/mac-10.15-bokken:v0.1.1-1022244
  flavor: m1.mac

variables:
  ARTIFACT_FILENAME: {{globals.artifact_base_name}}-osx-arm64.7z

commands:
# We don't test ARM64 yet, so let's build it on PRs targeting unity-main to make sure it builds at least
  - chmod 755 .yamato/scripts/build_osx_arm64.sh
  - ./.yamato/scripts/build_osx_arm64.sh

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"

artifacts:
  7z-archives:
    paths:
      - artifacts/unity/**
  build:
    paths:
      - artifacts/bin/**
