name: Build and Test Linux x64

agent:
  type: Unity::VM
  image: platform-foundation/linux-ubuntu-18.04-mono-bokken:0.1.7-978398
  flavor: b1.large

commands:
  - mkdir artifacts
  - curl https://public-stevedore.unity3d.com/r/public/7za-linux-x64/e6c75fb7ffda_e6a295cdcae3f74d315361883cf53f75141be2e739c020035f414a449d4876af.zip --output artifacts/7za-linux-x64.zip
  - unzip artifacts/7za-linux-x64.zip -d artifacts/7za-linux-x64
  - |
    cd unity/unitygc
    mkdir release
    cd release
    cmake -DCMAKE_BUILD_TYPE=Release ..
    cmake --build .
  - ./build.sh -subset clr+libs+libs -a x64 -c release -ci -ninja
  - cp unity/unitygc/release/libunitygc.so artifacts/bin/microsoft.netcore.app.runtime.linux-x64/Release/runtimes/linux-x64/native
  - artifacts/7za-linux-x64/7za a artifacts/unity/dotnet-runtime-unity-linux-x64.7z ./artifacts/bin/microsoft.netcore.app.runtime.linux-x64/Release/runtimes/linux-x64
# build/run tests
  - ./build.sh -subset libs.tests -test -a x64 -c release -ci -ninja
  - command: ./src/tests/build.sh x64 release ci
    retries: 1
  - ./src/tests/run.sh x64 release
  - ./build.sh clr.paltests
  - ./artifacts/bin/coreclr/$(uname).x64.Debug/paltests/runpaltests.sh $(pwd)/artifacts/bin/coreclr/$(uname).x64.Debug/paltests

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"

artifacts: 
  linux64:
    paths:
      - artifacts/unity/dotnet-runtime-unity-linux-x64.7z
