name: Build and Test Windows x64

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:latest
  flavor: b1.xlarge

commands:
  - build.cmd -subset clr+libs+libs.tests -test -a x64 -c release -ci
  - build.cmd -subset host+packs -a x64 -c release
  - src\tests\build.cmd x64 release ci
  - src\tests\run.cmd x64 release

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"

artifacts: 
  win64:
    paths:
      - artifacts\packages\Release\Shipping\dotnet-runtime-7.0.0-dev-win-x64.zip
