{% metadata_file .yamato/Globals.metafile %}
---
name: Generate OSX x64+ARM64

agent:
  type: Unity::VM::osx
  image: platform-foundation/mac-10.15-bokken:v0.1.1-1022244
  flavor: m1.mac

variables:
  ARTIFACT_FILENAME: {{globals.artifact_base_name}}-osx-x64arm64.7z

dependencies:
  - path: .yamato/build_test_osx_arm64.yml
  - path: .yamato/build_test_osx_x64.yml

commands:
# We don't test x64+ARM64 yet, so let's build it on PRs targeting unity-main to make sure it builds at least
  - chmod 755 .yamato/scripts/generate_osx_x64_arm64.sh
  - ./.yamato/scripts/generate_osx_x64_arm64.sh

artifacts:
  7z-archives:
    paths:
      - artifacts/unity/**
  build:
    paths:
      - artifacts/bin/**

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
