name: Build Classlibs Windows

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:stable
  flavor: b1.xlarge

commands:
  - .yamato/scripts/build_classlibs.bat

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"

artifacts: 
  win64:
    paths:
      - incomingbuilds\**