{% metadata_file .yamato/Globals.metafile %}
---
name: Test Windows x64

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:v1.1.7-1038262
  flavor: b1.xlarge

dependencies:
  - path: .yamato/build_windows_x64.yml

commands:
# build/run tests
  - dotnet build unity\managed.sln -c Release
  - |
    cd unity\embed_api_tests
    cmake .
    cmake --build . --config Release
    Release\mono_test_app.exe
  - build.cmd libs.tests -test /p:RunSmokeTestsOnly=true -a x64 -c release -ci
  - src\tests\build.cmd x64 release ci tree GC tree JIT tree baseservices tree interop tree reflection
  - src\tests\run.cmd x64 release

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
