{% metadata_file .yamato/Globals.metafile %}
---
name: Test Linux x64

agent:
  type: Unity::VM
  image: platform-foundation/linux-ubuntu-18.04-mono-bokken:0.1.7-978398
  flavor: b1.large

dependencies:
  - path: .yamato/build_linux_x64.yml

commands:
# build/run tests
#  - dotnet build unity/managed.sln -c Release
#  - |
#    cd unity/embed_api_tests
#    cmake -DCMAKE_BUILD_TYPE=Release .
#    cmake --build .
#    ./mono_test_app
  - ./build.sh -subset libs.tests -test /p:RunSmokeTestsOnly=true -a x64 -c release -ci -ninja
  - command: ./src/tests/build.sh x64 release ci -tree:GC -tree:JIT -tree:baseservices -tree:interop -tree:reflection
    retries: 1
  - ./src/tests/run.sh x64 release
  - ./build.sh clr.paltests
  - ./artifacts/bin/coreclr/$(uname).x64.Debug/paltests/runpaltests.sh $(pwd)/artifacts/bin/coreclr/$(uname).x64.Debug/paltests

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
