{% metadata_file .yamato/Globals.metafile %}
---
name: Test Windows x86

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:v1.1.7-1038262
  flavor: b1.xlarge

dependencies:
  - path: .yamato/build_windows_x86.yml

commands:
# build/run tests
  - dotnet build unity\managed.sln -c Release
#   - unity/run-embed-api-tests.cmd Release
  - build.cmd libs.tests -test -a x86 -c release -ci
  - src\tests\build.cmd x86 release ci
  - src\tests\run.cmd x86 release

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
